### ISSUE TITLE
Issue packaging solution

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/SecureScript7#2]
Had this issue while packaging solution for v1.0.0.01

![image](https://user-images.githubusercontent.com/49648086/156008412-0b4259cc-e860-4701-ab21-565ca46c4631.png)

![image](https://user-images.githubusercontent.com/49648086/156008427-147d1c83-ecc2-44f4-84ee-510f431e7fb0.png)

**Comment by mikezimm** [comment]
```bash
PS C:\Users\dev\Documents\GitHub\SecureScript7> gulp bundle --ship
Build target: SHIP
[10:13:08] Using gulpfile ~\Documents\GitHub\SecureScript7\gulpfile.js
[10:13:08] Starting 'bundle'...
[10:13:08] Starting gulp
[10:13:08] Starting subtask 'pre-copy'...
[10:13:09] Finished subtask 'pre-copy' after 45 ms
[10:13:09] Starting subtask 'copy-static-assets'...
[10:13:09] Starting subtask 'sass'...
[10:13:10] Finished subtask 'sass' after 1.25 s
[10:13:10] Starting subtask 'tslint'...
[10:13:10] [tslint] tslint version: 5.20.1
[10:13:10] Starting subtask 'tsc'...
[10:13:10] [tsc] typescript version: 3.9.10
[10:13:10] Finished subtask 'copy-static-assets' after 1.31 s
[10:13:13] Finished subtask 'tslint' after 3.37 s
[10:13:14] Finished subtask 'tsc' after 4.24 s
[10:13:14] Starting subtask 'post-copy'...
[10:13:14] Finished subtask 'post-copy' after 307 μs
[10:13:14] Starting subtask 'configure-webpack'...
[10:13:14] Finished subtask 'configure-webpack' after 336 ms
[10:13:14] Starting subtask 'webpack'...
{ Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at WorkerPool._createWorker (C:\Users\dev\Documents\GitHub\SecureScript7\node_modules\@rushstack\module-minifier-plugin\lib\workerPool\WorkerPool.js:129:35)
    at WorkerPool.checkoutWorkerAsync (C:\Users\dev\Documents\GitHub\SecureScript7\node_modules\@rushstack\module-minifier-plugin\lib\workerPool\WorkerPool.js:112:27)
    at WorkerPoolMinifier.minify (C:\Users\dev\Documents\GitHub\SecureScript7\node_modules\@rushstack\module-minifier-plugin\lib\WorkerPoolMinifier.js:60:14)
    at compilation.hooks.optimizeChunkAssets.tapPromise (C:\Users\dev\Documents\GitHub\SecureScript7\node_modules\@rushstack\module-minifier-plugin\lib\ModuleMinifierPlugin.js:285:38)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\dev\Documents\GitHub\SecureScript7\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:17)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\dev\Documents\GitHub\SecureScript7\node_modules\tapable\lib\Hook.js:154:20) code: 'MODULE_NOT_FOUND' }
[10:13:19] Error - [webpack] 'dist':
Cannot find module 'worker_threads'
Cannot find module 'worker_threads'
Cannot find module 'worker_threads'



Cannot find module 'worker_threads'
Cannot find module 'worker_threads'

[10:13:20] Project secure-script-7 version:0.1.01
[10:13:20] Build tools version:3.17.17
[10:13:20] Node version:v10.24.1
[10:13:20] Total duration:13 s
[10:13:20] Task errors:1
The build failed because a task wrote output to stderr.
Exiting with exit code: 1
PS C:\Users\dev\Documents\GitHub\SecureScript7> gulp package-solution --ship
Build target: SHIP
[10:15:08] Using gulpfile ~\Documents\GitHub\SecureScript7\gulpfile.js
[10:15:08] Starting 'package-solution'...        
[10:15:08] Starting gulp
[10:15:08] Starting subtask 'package-solution'...
[10:15:08] Error - [package-solution] No manifests were found in 'C:\Users\dev\Documents\GitHub\SecureScript7\release/manifests'. Ensure a build has completed successfully
[10:15:08] Finished subtask 'package-solution' after 31 ms
[10:15:08] Finished 'package-solution' after 35 ms        
[10:15:09] ==================[ Finished ]==================
Error - [package-solution] No manifests were found in 'C:/Users/dev/Documents/GitHub/SecureScript7/release/manifests'. Ensure a build has completed successfully
[10:15:09] Project secure-script-7 version:0.1.01
[10:15:09] Build tools version:3.17.17
[10:15:09] Node version:v10.24.1      
[10:15:09] Total duration:3.15 s      
[10:15:09] Task errors:1
The build failed because a task wrote output to stderr.
Exiting with exit code: 1
PS C:\Users\dev\Documents\GitHub\SecureScript7> 
```

**Comment by mikezimm** [comment]
## npm install errors and warnings

![image](https://user-images.githubusercontent.com/49648086/156009306-47c8ec4c-3077-476d-9eb2-9ec1022d445a.png)


[10:20:04] Total duration:3.15 s
PS C:\Users\dev\Documents\GitHub\SecureScript7> npm install
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/common@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/logging@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/odata@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-clientsvc@1.3.11 requires a peer of @pnp/sp@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/logging@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/common@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/odata@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN @pnp/sp-taxonomy@1.3.11 requires a peer of @pnp/sp@1.3.11 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\@rushstack\typings-generator\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 2565 packages in 10.582s

123 packages are looking for funding
  run `npm fund` for details

found 135 vulnerabilities (19 low, 73 moderate, 40 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\dev\Documents\GitHub\SecureScript7> gulp clean
